// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//服务器发送给客户端通知玩家的pid
type SyncPid struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPid) Reset()         { *m = SyncPid{} }
func (m *SyncPid) String() string { return proto.CompactTextString(m) }
func (*SyncPid) ProtoMessage()    {}
func (*SyncPid) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SyncPid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPid.Unmarshal(m, b)
}
func (m *SyncPid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPid.Marshal(b, m, deterministic)
}
func (m *SyncPid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPid.Merge(m, src)
}
func (m *SyncPid) XXX_Size() int {
	return xxx_messageInfo_SyncPid.Size(m)
}
func (m *SyncPid) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPid.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPid proto.InternalMessageInfo

func (m *SyncPid) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

//服务器广播消息
type BroadCast struct {
	Pid int32 `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Tp  int32 `protobuf:"varint,2,opt,name=Tp,proto3" json:"Tp,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*BroadCast_Content
	//	*BroadCast_P
	//	*BroadCast_AcctionData
	Data                 isBroadCast_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BroadCast) Reset()         { *m = BroadCast{} }
func (m *BroadCast) String() string { return proto.CompactTextString(m) }
func (*BroadCast) ProtoMessage()    {}
func (*BroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *BroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadCast.Unmarshal(m, b)
}
func (m *BroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadCast.Marshal(b, m, deterministic)
}
func (m *BroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadCast.Merge(m, src)
}
func (m *BroadCast) XXX_Size() int {
	return xxx_messageInfo_BroadCast.Size(m)
}
func (m *BroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_BroadCast proto.InternalMessageInfo

func (m *BroadCast) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *BroadCast) GetTp() int32 {
	if m != nil {
		return m.Tp
	}
	return 0
}

type isBroadCast_Data interface {
	isBroadCast_Data()
}

type BroadCast_Content struct {
	Content string `protobuf:"bytes,3,opt,name=Content,proto3,oneof"`
}

type BroadCast_P struct {
	P *Position `protobuf:"bytes,4,opt,name=P,proto3,oneof"`
}

type BroadCast_AcctionData struct {
	AcctionData int32 `protobuf:"varint,5,opt,name=AcctionData,proto3,oneof"`
}

func (*BroadCast_Content) isBroadCast_Data() {}

func (*BroadCast_P) isBroadCast_Data() {}

func (*BroadCast_AcctionData) isBroadCast_Data() {}

func (m *BroadCast) GetData() isBroadCast_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BroadCast) GetContent() string {
	if x, ok := m.GetData().(*BroadCast_Content); ok {
		return x.Content
	}
	return ""
}

func (m *BroadCast) GetP() *Position {
	if x, ok := m.GetData().(*BroadCast_P); ok {
		return x.P
	}
	return nil
}

func (m *BroadCast) GetAcctionData() int32 {
	if x, ok := m.GetData().(*BroadCast_AcctionData); ok {
		return x.AcctionData
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BroadCast) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BroadCast_Content)(nil),
		(*BroadCast_P)(nil),
		(*BroadCast_AcctionData)(nil),
	}
}

type Position struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	V                    float32  `protobuf:"fixed32,4,opt,name=V,proto3" json:"V,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Position) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Position) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

//定义聊天协议
type Talk struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Talk) Reset()         { *m = Talk{} }
func (m *Talk) String() string { return proto.CompactTextString(m) }
func (*Talk) ProtoMessage()    {}
func (*Talk) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Talk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Talk.Unmarshal(m, b)
}
func (m *Talk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Talk.Marshal(b, m, deterministic)
}
func (m *Talk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Talk.Merge(m, src)
}
func (m *Talk) XXX_Size() int {
	return xxx_messageInfo_Talk.Size(m)
}
func (m *Talk) XXX_DiscardUnknown() {
	xxx_messageInfo_Talk.DiscardUnknown(m)
}

var xxx_messageInfo_Talk proto.InternalMessageInfo

func (m *Talk) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//定义一个玩家显示结构
type SyncPlayerProto struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SyncPlayerProto) Reset()         { *m = SyncPlayerProto{} }
func (m *SyncPlayerProto) String() string { return proto.CompactTextString(m) }
func (*SyncPlayerProto) ProtoMessage()    {}
func (*SyncPlayerProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *SyncPlayerProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPlayerProto.Unmarshal(m, b)
}
func (m *SyncPlayerProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPlayerProto.Marshal(b, m, deterministic)
}
func (m *SyncPlayerProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPlayerProto.Merge(m, src)
}
func (m *SyncPlayerProto) XXX_Size() int {
	return xxx_messageInfo_SyncPlayerProto.Size(m)
}
func (m *SyncPlayerProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPlayerProto.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPlayerProto proto.InternalMessageInfo

func (m *SyncPlayerProto) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Player struct {
	Pid                  int32     `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	P                    *Position `protobuf:"bytes,2,opt,name=P,proto3" json:"P,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Player) GetP() *Position {
	if m != nil {
		return m.P
	}
	return nil
}

func init() {
	proto.RegisterType((*SyncPid)(nil), "SyncPid")
	proto.RegisterType((*BroadCast)(nil), "BroadCast")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*Talk)(nil), "Talk")
	proto.RegisterType((*SyncPlayerProto)(nil), "SyncPlayerProto")
	proto.RegisterType((*Player)(nil), "Player")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xb4, 0x30,
	0x10, 0xc6, 0x99, 0xc2, 0xc2, 0xcb, 0xf0, 0xfa, 0x27, 0xbd, 0x58, 0xf5, 0x82, 0x3d, 0x71, 0xe2,
	0xb0, 0xeb, 0x17, 0x90, 0xf5, 0xc0, 0xb1, 0xa9, 0x64, 0xb3, 0xbb, 0xb7, 0x0a, 0xc4, 0x10, 0x57,
	0x4a, 0xa0, 0x97, 0xfd, 0x16, 0x7e, 0x64, 0xd3, 0x6e, 0x50, 0xa3, 0x9e, 0xda, 0xe7, 0x99, 0x74,
	0xfa, 0x9b, 0x67, 0xf0, 0xec, 0xad, 0x9d, 0x26, 0xf5, 0xd2, 0xe6, 0xc3, 0xa8, 0x8d, 0xe6, 0xb7,
	0x18, 0x3d, 0x1d, 0xfb, 0x5a, 0x74, 0x0d, 0xbd, 0x44, 0x5f, 0x74, 0x0d, 0x83, 0x14, 0xb2, 0x85,
	0xb4, 0x57, 0xfe, 0x0e, 0x18, 0x17, 0xa3, 0x56, 0xcd, 0x5a, 0x4d, 0xe6, 0x77, 0x9d, 0x9e, 0x23,
	0xa9, 0x06, 0x46, 0x9c, 0x41, 0xaa, 0x81, 0xde, 0x60, 0xb4, 0xd6, 0xbd, 0x69, 0x7b, 0xc3, 0xfc,
	0x14, 0xb2, 0xb8, 0xf4, 0xe4, 0x6c, 0xd0, 0x6b, 0x04, 0xc1, 0x82, 0x14, 0xb2, 0x64, 0x19, 0xe7,
	0x42, 0x4f, 0x9d, 0xe9, 0x74, 0x5f, 0x7a, 0x12, 0x04, 0xe5, 0x98, 0x3c, 0xd4, 0xb5, 0xd5, 0x8f,
	0xca, 0x28, 0xb6, 0xb0, 0xfd, 0x4a, 0x4f, 0x7e, 0x37, 0x8b, 0x10, 0x03, 0x7b, 0xf2, 0x02, 0xff,
	0xcd, 0x8f, 0xe9, 0x7f, 0x84, 0xad, 0xc3, 0x21, 0x12, 0xb6, 0x56, 0xed, 0x1c, 0x0b, 0x91, 0xb0,
	0xb3, 0x6a, 0xef, 0x20, 0x88, 0x84, 0xbd, 0x55, 0x1b, 0xf7, 0x39, 0x91, 0xb0, 0xe1, 0x29, 0x06,
	0x95, 0x3a, 0xbc, 0x52, 0xf6, 0x85, 0x6b, 0xbb, 0xc4, 0x9f, 0xb0, 0xfc, 0x1e, 0x2f, 0x5c, 0x2a,
	0x07, 0x75, 0x6c, 0x47, 0x61, 0x83, 0xa2, 0x77, 0x18, 0x0d, 0x4e, 0x4e, 0x0c, 0x52, 0x3f, 0x4b,
	0x96, 0x51, 0x7e, 0x2a, 0xcb, 0xd9, 0xe7, 0x2b, 0x0c, 0x4f, 0xd6, 0x1f, 0x51, 0x5d, 0xd9, 0xf1,
	0xc9, 0x8f, 0xf1, 0x25, 0x88, 0xe7, 0xd0, 0xed, 0x61, 0xf5, 0x11, 0x00, 0x00, 0xff, 0xff, 0xf2,
	0xd3, 0x2b, 0x96, 0x98, 0x01, 0x00, 0x00,
}
